import React from "react";
import CardContent from "@material-ui/core/CardContent";
import Card from "@material-ui/core/Card";
import {makeStyles} from "@material-ui/core/styles";
import Grid from "@material-ui/core/Grid";
import Typography from "@material-ui/core/Typography";
import Divider from "@material-ui/core/Divider";

const useStyles = makeStyles({
    root: {
        minWidth: 275,
    }
});

const About = () => {

  const classes = useStyles();
  return <Grid container spacing={3}>
      <Grid item xs={6}>
          <Card className={classes.root}>
              <CardContent className={classes.grid}>
              <Typography variant="h5" component="h2">
                  Overview
              </Typography>
              <Divider />
              <br />
              <div style={{
                  fontSize: '15px',
                  textAlign: 'justify',
                  height: '500px'
              }}>
              Air pollution is a serious global problem that, according to the World Health Organization (WHO), causes about seven million deaths per year today, even seven times more deaths than COVID-19. It is estimated that nine out of ten people breathe polluted air all over the planet. These data cause amazement, since the tendency is for the population to be exposed to progressively higher levels of air pollutants, over time, if nothing is done. Nowadays, 55% of this one lives in urban areas, where pollutants are more concentrated, and this proportion is expected to increase to 70% by 2050, being an aggravating factor of the global situation. Air pollution, in addition to being a great risk to environmental health, is also an alarming danger to human health, because it is associated with a higher incidence of respiratory diseases.
              <br />
              <br />
              This scenario increasingly distances us directly from two of the United Nations (UN) the 17 Sustainable Development Goals: "Climate Action" and "Good Health and Well-Being", making it difficult to transform the world into a better place. Faced with the intense health crisis we are experiencing due to COVID-19 and its numerous developments, it is clear how difficult it is to breathe under the use of masks and do it in an air of doubtful composition, in which we cannot see whether or not the virus is present. If we remain inertial about the problem of air pollution, over the years, we can be deprived of practicing freely and without the use of other devices what guarantees us life: breathing.
              </div>
              </CardContent>
          </Card>
      </Grid>
      <br/>
      <Grid item xs={6}>
          <Card className={classes.root}>
              <CardContent className={classes.grid}>
                  <Typography variant="h5" component="h2">
                      Our challenge
                  </Typography>
                  <Divider />
                  <br />
                  <div style={{
                      fontSize: '15px',
                      textAlign: 'justify',
                      height: '500px'
                  }}>
                  Our challenge is to study the effects of air pollution, integrating different types of data sets and applications, with an interdisciplinary approach and use of Earth sciences and health sciences. Therefore, we must create tools that make observation data more accessible for use by scientists, decision-makers and the public, in order to develop a better understanding of the links between air quality and human health and increase knowledge of data from NASA, ESA, JAXA, CNES and CSA worldwide.
                  <br/>
                  <br />
                  Thus, it’s essential to warn individuals about the dangers generated by air pollution to the particular health of each one and public health, in a practical and uncomplicated way, in addition to bringing out negative impacts of this problem in other spheres (such as fauna and flora) that often go unnoticed and affect, even indirectly, society, because they are harming the planet, It is necessary to raise awareness about the urgency of curbing air pollution, a subject that ends up being trivialized or left aside in people's minds, not receiving due attention.
                  <br/>
                  <br />
                  Also, in order to allow a more solid, fast and safer planning by decision makers, it is interesting and useful to predict diseases over time caused by maintaining the current levels of pollutants present in the atmosphere, as well as the availability of information about comorbidities that already affect the population and their possible connections with the type of pollution in each location and its origin, facilitating the studies of research institutions.
                  </div>
              </CardContent>
          </Card>
      </Grid>
      <br/>
      <Grid item xs={6}>
          <Card className={classes.root}>
              <CardContent className={classes.grid}>
                  <Typography variant="h5" component="h2">
                      Our solution
                  </Typography>
                  <Divider />
                  <br />
                  <div style={{
                      fontSize: '15px',
                      textAlign: 'justify',
                      height: '500px'
                  }}>
                  We created a website that points out a practical score of general pollution in real time, according to the amount of different types of air pollutants, between gases and particles, present according to the user's location, which indicates their comorbidities, age and sex, and thus certifies a personalized experience focused on the individual. The platform also exposes the evolution of general pollution, the history of air pollutants and provides the user with the comparison of the indices of the place where he is with the world average, including conducts for prevention and health promotion through recommendations according to the local air situation at the time and the diseases that the user presents.
                  <br/>
                  <br />
                  The project, seeking to raise awareness and inform the population, shows clear connections between air pollution and foreign affairs such as COVID-19, fires, corals and global warming. The medical basis and the protection of user data are guaranteed on the site, through which we hope to mainly reach people from large cities, with a high incidence of COVID-19.
                  <br/>
                  <br />
                  In addition, we use mathematical modeling to predict diseases and symptoms that can be developed or aggravated within different deadlines, according to the levels of each type of pollutant in the air of a given location and other climatic factors, in cases of acute and chronic exposure. "Annie" artificial intelligence will be available to answer questions instantly and there will be a ChatBot for better customer interaction, quickly and accessible.
                  </div>
              </CardContent>
          </Card>
      </Grid>
      <br/>
      <Grid item xs={6}>
          <Card className={classes.root}>
              <CardContent className={classes.grid}>
                  <Typography variant="h5" component="h2">
                      Why is it important?
                  </Typography>
                  <Divider />
                  <br />
                  <div style={{
                      fontSize: '15px',
                      textAlign: 'justify',
                      height: '500px'
                  }}>
                  Informing people, with practicality and dynamism, about the threats generated by air pollution in relation to their health is fundamental for the development of awareness about the enormous dimensions of the phenomenon. In addition, explaining its connections with other points, which cause damage to the individual and the planet completely, contributes to the evolution of a sustainable mentality in more expressive portions of humanity, giving the air pollution agenda the focus and urgency that is due, removing it from the darkness of denialism, trivialization and disinformation. Thus, it is possible to move the population from passive reality to an active mass posture on the subject, crucial for the preservation of the planet and positive changes, aiming at a promising future.
                  <br/>
                  <br />
                  The registration on the site involving comorbidities, sex, age and user location also forms a database that can be used for studies and research by institutions, which can, as well as citizens in general, access the history of general pollution and each air pollutant.
                  <br/>
                  <br />
                  Furthermore, on the other hand, our project allows the observation of the relationship between the types and levels of air pollutants with the development of symptoms and diseases, making accurate and comprehensive predictions, with a medical, scientific basis, on reliable data from satellites and locality in real time, which help decision makers, scientists and health agents in planning actions and directing funds, which reduces waste of time, adds precision and, as a consequence, promotes public welfare and saves lives, elements that are so important when talking about health.
                  </div>
              </CardContent>
          </Card>
      </Grid>
      <br/>
      <Grid item xs={12}>
          <Card className={classes.root}>
              <CardContent className={classes.grid}>
                  <Typography variant="h5" component="h2">
                      Future plans
                  </Typography>
                  <Divider />
                  <br />
                  <div style={{
                      fontSize: '15px',
                      textAlign: 'justify',
                      height: '200px'
                  }}>
                  We hope to get the support of NASA and other integrated space agencies to expand our project and thus raise awareness and help thousands of people, keeping them informed and connected with their health. For this, we aim to:
                  <br />
                  <br />
                  <ul style={{
                      marginTop: 0,
                  }}>
                      <li> Expand our capacity to use satellite data, with the use of a smaller grid, so that we can be more accurate in the user's location</li>
                      <li> Provide the reach of our solution to as many locations as possible</li>
                      <li> Accumulate a significant information database in order to contribute in the areas of research and studies</li>
                  </ul>
                  </div>
              </CardContent>
          </Card>
      </Grid>


    </Grid>
};


export default About;